### ISSUE TITLE
Upsolving should contribute a 0.5 multiplier

### ISSUE THREAD

**Issue by pavan-kalyan** [neal2018/cp-ranking#14]
According to what the prof said in class, I think upsolving should contribute to half of what one would have scored during the live contest.
ref: https://edstem.org/us/courses/35824/discussion/2599400

It seems like this might be a trivial change ( 0 -> 0.5) in https://github.com/neal2018/cp-ranking/blob/becc78c3be27fce1ca6a7090fe5377db6e5f07a1/src/composables/utils.ts#L50-L52

If the change sounds fine, I can raise a PR.

**Comment by neal2018** [comment]
Sounds correct to me. c.c. @Akash-Nayar

**Comment by Akash-Nayar** [comment]
this is correct, however, some students have abused this issue by simply copy and pasting solutions for problems they don't know how to solve, so the professor and I are thinking of a solution. possibly we will void those submissions which were blindly copy and pasted without any understanding. i will work on this starting Wednesday.
